### ISSUE TITLE
Service Accounts : Path Error

### ISSUE THREAD

**Issue by iminamoto** [TheCaduceus/Multi-Cloud-Transfer-Tool#12]

**Comment by TheCaduceus** [comment]
@iminamoto By seeing your given Traceback, it is clear that you are trying to use your Service Accounts. For your information! while using Service Accounts to make your rclone remotes, you need to provide the path of one `.json` file otherwise providing any other path or invalid path trigger this Error because Rclone was not able to show Shared Drive list due to lack of credentials which it collects from `.json` files. I do like to recommend you to read [Rclone Docs](https://rclone.org/docs/) before opening any issue here.
