### ISSUE TITLE
Torrent - Select files to be downloaded

### ISSUE THREAD

**Issue by NourElDeen05** [TheCaduceus/Multi-Cloud-Transfer-Tool#13]
I'm not able to select which files to be downloaded, as the torrent some times has multiple files grater than 15gb whish is the Google drive capacity.

**Comment by TheCaduceus** [comment]
@NourElDeen05 MCT Tool uses LibTorrent as Torrent downloader because it is lightweight and hence lack Torrent file selection feature, using any other Torrent Engine can simply terminate your access from Google Colab.

Workaround:
Use Shared Drive which can have TBs of free space as destination in case of Google Drive or choose any other cloud storage.
