### ISSUE TITLE
"Transport endpoint is not connected" 

### ISSUE THREAD

**Issue by oknchm** [TheCaduceus/Multi-Cloud-Transfer-Tool#2]
I want to copy files from Google Drive to Microsoft OneDrive, but during the process, the remotes just unmount on their own thus unsuccessfully copying the files. I tried to copy with and without using the Time Out Preventer, but same results. Hoping you can help me, thank you very much!

![1-1](https://user-images.githubusercontent.com/86455151/161402812-426ed18a-f144-410e-b57c-45ff65ccc8d4.png)
![1-3](https://user-images.githubusercontent.com/86455151/161402816-ad461612-0596-4d25-984e-50d7296cbace.png)
![1-4](https://user-images.githubusercontent.com/86455151/161402818-f54f8674-ce20-431b-bb91-a0eb6af35240.png)
![1-5](https://user-images.githubusercontent.com/86455151/161402820-9dd0d09d-e7fe-4b37-8ed9-7512d615e629.png)

**Comment by SidIlliciT** [comment]
Hi, I tried copying a 1 gig folder from one drive to gdrive all went fine without any issues.
Have you fo sure enabled the Timeout Preventer ?

**Comment by TheCaduceus** [comment]
> I want to copy files from Google Drive to Microsoft OneDrive, but during the process, the remotes just unmount on their own thus unsuccessfully copying the files. I tried to copy with and without using the Time Out Preventer, but same results. Hoping you can help me, thank you very much!
> 
> ![1-1](https://user-images.githubusercontent.com/86455151/161402812-426ed18a-f144-410e-b57c-45ff65ccc8d4.png) ![1-3](https://user-images.githubusercontent.com/86455151/161402816-ad461612-0596-4d25-984e-50d7296cbace.png) ![1-4](https://user-images.githubusercontent.com/86455151/161402818-f54f8674-ce20-431b-bb91-a0eb6af35240.png) ![1-5](https://user-images.githubusercontent.com/86455151/161402820-9dd0d09d-e7fe-4b37-8ed9-7512d615e629.png)

Thanks for creating your issue! After searching about this Error on Rclone forums and other Websites , I did not find anything. So I can confirm that this problem is not from Rclone or Program itself | But when I checked your attached Images, then I found something unusual that client is not showing how much ram or disk space is occupied! So I recommend to Change your Runtime by going into Runtime Tab -> Change Runtime -> Choose TPU or GPU as you like. This confirms that problem is in the Runtime you connected with!
![image](https://user-images.githubusercontent.com/87380104/161416107-ca64c41a-b51f-49e1-b7b8-e740118704f0.png)

**Comment by oknchm** [comment]
> Hi, I tried copying a 1 gig folder from one drive to gdrive all went fine without any issues. Have you fo sure enabled the Timeout Preventer ?

I'm copying files from Google Drive to OneDrive, not the other way around. Though I tried copying a 3.85gb file from OD to GD and it seemed to work well? It's GD to OD that I'm having a problem with.

And yes, I'm sure I enabled the Timeout Preventer.

**Comment by oknchm** [comment]
> Thanks for creating your issue! After searching about this Error on Rclone forums and other Websites , I did not find anything. So I can confirm that this problem is not from Rclone or Program itself | But when I checked your attached Images, then I found something unusual that client is not showing how much ram or disk space is occupied! So I recommend to Change your Runtime by going into Runtime Tab -> Change Runtime -> Choose TPU or GPU as you like. This confirms that problem is in the Runtime you connected with! ![image](https://user-images.githubusercontent.com/87380104/161416107-ca64c41a-b51f-49e1-b7b8-e740118704f0.png)

Sorry about that, I was using the Dark Reader extension on my browser so it messed with the colors. 

![Screenshot (156)](https://user-images.githubusercontent.com/86455151/161441561-def72774-e70e-436b-8dc0-056905cfec1a.png)

I used both GPU and TPU. I don't get the "transport endpoint is not connected" error anymore, but I still can't copy everything successfully.

I tried to copy a 3.7gb folder (w/ 2 videos - 2.7gb+1.03gb). The 1.03gb file got copied but the 2.7gb one was just stuck. It says 100% but when I check OneDrive, it's not uploaded at all.

![Screenshot (158)](https://user-images.githubusercontent.com/86455151/161445238-efe6b9f4-203e-4141-9da0-75984f2b22be.png)

And when I stopped/interrupted the process, the remotes were unmounted.

![Screenshot (161)](https://user-images.githubusercontent.com/86455151/161445373-6249c1dd-480a-4754-8e86-1346d4c328f4.png)

**Comment by TheCaduceus** [comment]
> 

---
There ^C is written because you have interrupted the process before it completes, and Drives get unmounted because you may clicked the Interrupt button 3 Times and the runtime got restart after considering that Code can't be paused. And if I talk about Files showing to be successfully copied from Google Drive to OneDrive then this problem is from Rclone's Side, and I also did not found anything useful. It will be useful if you submit this Problem on http://rclone.org/
